printf("\n");
puts("-------------------------------------");
puts("|         IDENTIFICADORES           |");
puts("-------------------------------------");
puts("Un identificador es una secuencia de");
puts("caracteres, letras, digitos y guion _ ");
puts("el primer caracter debe ser una letra");
puts("algunos compiladores admiten _ inicial");
puts("mayusculas y minusculas son diferentes");
puts("-------------------------------------");
puts("|     IDENTIFICADORES VALIDOS       |");
puts("-------------------------------------");
puts("|             nombre_clase          |");
puts("|             elemento_mayor        |");
puts("|                  a                |");
puts("|               Indice              |");
puts("|             Cantidad_Total        |");
puts("|             Habitacion120         |");
puts("|             Dia_Mes_Anyo          |");
puts("|             Fecha_Compra_Casa     |");
puts("|                  i                |");
puts("-------------------------------------");