printf("\n");
puts("-------------------------------------");
puts("|         PALABRAS RESERVADAS       |");
puts("-------------------------------------");
puts("los siguientes identificadores estan");
puts("reservados para utilizarlos como");
puts("palabras reservadas, y no se deben");
puts("emplear para otros propositos");
puts("-------------------------------------");
puts("|             asm                   |");
puts("|             auto                  |");
puts("|             break                 |");
puts("|             case                  |");
puts("|             enum                  |");
puts("|             extern                |");
puts("|             float                 |");
puts("|             for                   |");
puts("|             signed                |");
puts("|             sizeof                |");
puts("|             static                |");
puts("|             struct                |");
puts("|             char                  |");
puts("|             const                 |");
puts("|             continue              |");
puts("|             default               |");
puts("|             do                    |");
puts("|             double                |");
puts("|             else                  |");
puts("|             goto                  |");
puts("|             if                    |");
puts("|             int                   |");
puts("|             long                  |");
puts("|             register              |");
puts("|             return                |");
puts("|             short                 |");
puts("|             switch                |");
puts("|             typedef               |");
puts("|             union                 |");
puts("|             unsigned              |");
puts("|             void                  |");
puts("|             volatile              |");
puts("|             while                 |");
puts("-------------------------------------");