printf("\n");
puts("-------------------------------------");
puts("|        Secuencias de escape       |");
puts("-------------------------------------");
puts("| codigo de escape |    significado |");
puts("-------------------------------------");
printf("|--'%cn'---------|--nueva linea------|\n",92);
printf("|--'%cr'---------|--retorno de carro-|\n",92);
printf("|--'%ct'---------|--tabulacion-------|\n",92);
printf("|--'%cv'---------|tabulacion vertical|\n",92);
printf("|--'%ca'-------|alerta(pitido sonoro)|\n",92);
printf("|--'%cb'-------|-retroceso de espacio|\n",92);
printf("|--'%cf'---------|--avance de pagina-|\n",92);
printf("|--'%c%c'----|-barra inclinada inversa|\n",92,92);
printf("|--'%c''---------|----comilla simple-|\n",92);
printf("|--'%c\"'--------|-----comilla doble--|\n",92);
printf("|--'%c?'---|--signo de interrogacion-|\n",92);
printf("|--'%c000'-------|----numero octal---|\n",92);
printf("|--'%cxhh'-----|--numero hexadecimal-|\n",92);
printf("-------------------------------------");