puts("-------------------------------------");
printf("| Bienvenido a la programacion en C |\n");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("iniciando programa mensaje ...");
puts("-------------------------------------");
printf("\n");
#include "Mensaje.c"
printf("\n");
puts("-------------------------------------");
puts("iniciando programa longitud curcunferencia ...");
puts("-------------------------------------");
printf("\n");
#include "LongitudCircunferencia.c"
printf("\n");
puts("-------------------------------------");
puts("Frase atribuida a : ");
puts("Dijkstra - A principios de los setenta");
puts("-------------------------------------");
puts("Las pruebas solo muestran la presencia de errores,");
puts("no su ausencia. No se puede probar que un programa");
puts("es correcto (exacto) solo se puede mostrar que es incorrecto");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("Tokens (elementos lexicos de los programas)");
puts("-------------------------------------");
puts("Existen cinco clases de tokens:");
puts("1- identificadores");
puts("2- palabras reservadas");
puts("3- literales");
puts("4- operadores y");
puts("5- otros separadores");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("|         IDENTIFICADORES           |");
puts("-------------------------------------");
puts("Un identificador es una secuencia de");
puts("caracteres, letras, digitos y guion _ ");
puts("el primer caracter debe ser una letra");
puts("algunos compiladores admiten _ inicial");
puts("mayusculas y minusculas son diferentes");
puts("-------------------------------------");
puts("|     IDENTIFICADORES VALIDOS       |");
puts("-------------------------------------");
puts("|             nombre_clase          |");
puts("|             elemento_mayor        |");
puts("|                  a                |");
puts("|               Indice              |");
puts("|             Cantidad_Total        |");
puts("|             Habitacion120         |");
puts("|             Dia_Mes_Anyo          |");
puts("|             Fecha_Compra_Casa     |");
puts("|                  i                |");
puts("-------------------------------------");