puts("-------------------------------------");
printf("| Bienvenido a la programacion en C |\n");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("iniciando programa mensaje ...");
puts("-------------------------------------");
printf("\n");
#include "Mensaje.c"
printf("\n");
puts("-------------------------------------");
puts("iniciando programa longitud curcunferencia ...");
puts("-------------------------------------");
printf("\n");
#include "LongitudCircunferencia.c"
printf("\n");
puts("-------------------------------------");
puts("Frase atribuida a : ");
puts("Dijkstra - A principios de los setenta");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("Las pruebas solo muestran la presencia de errores,");
puts("no su ausencia. No se puede probar que un programa");
puts("es correcto (exacto) solo se puede mostrar que es incorrecto");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("Tokens (elementos lexicos de los programas)");
puts("-------------------------------------");
puts("Existen cinco clases de tokens:");
puts("1- identificadores");
puts("2- palabras reservadas");
puts("3- literales");
puts("4- operadores y");
puts("5- otros separadores");
puts("-------------------------------------");
