puts("-------------------------------------");
printf("| Bienvenido a la programacion en C |\n");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("iniciando programa mensaje ...");
puts("-------------------------------------");
printf("\n");
#include "Mensaje.c"
printf("\n");
puts("-------------------------------------");
puts("iniciando programa longitud curcunferencia ...");
puts("-------------------------------------");
printf("\n");
#include "LongitudCircunferencia.c"
printf("\n");
puts("-------------------------------------");
puts("Frase atribuida a : ");
puts("Dijkstra - A principios de los setenta");
puts("-------------------------------------");
puts("Las pruebas solo muestran la presencia de errores,");
puts("no su ausencia. No se puede probar que un programa");
puts("es correcto (exacto) solo se puede mostrar que es incorrecto");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("Tokens (elementos lexicos de los programas)");
puts("-------------------------------------");
puts("Existen cinco clases de tokens:");
puts("1- identificadores");
puts("2- palabras reservadas");
puts("3- literales");
puts("4- operadores y");
puts("5- otros separadores");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("|         IDENTIFICADORES           |");
puts("-------------------------------------");
puts("Un identificador es una secuencia de");
puts("caracteres, letras, digitos y guion _ ");
puts("el primer caracter debe ser una letra");
puts("algunos compiladores admiten _ inicial");
puts("mayusculas y minusculas son diferentes");
puts("-------------------------------------");
puts("|     IDENTIFICADORES VALIDOS       |");
puts("-------------------------------------");
puts("|             nombre_clase          |");
puts("|             elemento_mayor        |");
puts("|                  a                |");
puts("|               Indice              |");
puts("|             Cantidad_Total        |");
puts("|             Habitacion120         |");
puts("|             Dia_Mes_Anyo          |");
puts("|             Fecha_Compra_Casa     |");
puts("|                  i                |");
puts("-------------------------------------");
printf("\n");
puts("-------------------------------------");
puts("|         PALABRAS RESERVADAS       |");
puts("-------------------------------------");
puts("los siguientes identificadores estan");
puts("reservados para utilizarlos como");
puts("palabras reservadas, y no se deben");
puts("emplear para otros propositos");
puts("-------------------------------------");
puts("|            asm                    |");
puts("|             auto                  |");
puts("|                  break            |");
puts("|               case                |");
puts("|             enum                  |");
puts("|             extern                |");
puts("|             float                 |");
puts("|             for                   |");
puts("|             signed                |");
puts("|             sizeof                |");
puts("|             static                |");
puts("|             struct                |");
puts("|             char                  |");
puts("|             const                 |");
puts("|             continue              |");
puts("|             default               |");
puts("|             do                    |");
puts("|             double                |");
puts("|             else                  |");
puts("|             goto                  |");
puts("|             if                    |");
puts("|             int                   |");
puts("|             long                  |");
puts("|             register              |");
puts("|             return                |");
puts("|             short                 |");
puts("|             switch                |");
puts("|             typedef               |");
puts("|             union                 |");
puts("|             unsigned              |");
puts("|             void                  |");
puts("|             volatile              |");
puts("|             while                 |");
puts("-------------------------------------");