puts("\n");
puts("-------------------------------------");
puts("------TIPOS DE DATOS SIMPLES---------");
puts("-------------------------------------");
puts("C no soporta una gran cantidad de tipos");
puts("de datos predefinidos, pero tiene");
puts("la capacidad para crear sus propios");
puts("tipos de datos");
puts("-------------------------------------");
puts("Los tipos de datos simples de c son :");
puts("-------------------------------------");
puts("|             char                  |");
puts("|             short                 |");
puts("|             int                   |");
puts("|             unsigned int          |");
puts("|             long                  |");
puts("|             float                 |");
puts("|             double                |");
puts("|             long double           |");
puts("-------------------------------------");